reorder safety comments and attributes
This avoids clippy errors in old versions of clippy (here 1.78):

    error: unsafe impl missing a safety comment
        --> src/lib.rs:1677:9
         |
    1677 |         unsafe impl<$ret, $($rest),*> ZeroableOption for $($prefix)* fn($($rest),*) -> $ret {}
         |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...
    1682 | impl_fn_zeroable_option!(["Rust", "C"] { A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U });
         | --------------------------------------------------------------------------------------------------------- in this macro invocation
         |
         = help: consider adding a safety comment on the preceding line
         = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#undocumented_unsafe_blocks
         = note: this error originates in the macro `impl_fn_zeroable_option` (in Nightly builds, run with -Z macro-backtrace for more info)

Fixes: 530c4eb79a44 ("doc: de-clutter documentation with fake-variadics")
Signed-off-by: Benno Lossin <lossin@kernel.org>